[package]
name = "yml2mp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eva-common = "0.1.67"
serde_yaml = "0.8.23"
rmp-serde = "1.0.0"
